<?php // only copy this line if needed

/**
 * Adds the order barcode generated by WooCommerce Order Barcodes
 * to the bottom of invoices
 *
 * @param string $type the document type
 * @param string $action current action running on Document
 * @param \WC_PIP_Document $document document object
 * @param \WC_Order $order order object
 */
function sv_wc_pip_add_order_barcode( $type, $action, $document, $order ) {

	if ( function_exists( 'WC_Order_Barcodes' ) && 'invoice' === $type && $order instanceof WC_Order ) {
		WC_Order_Barcodes()->get_display_barcode( $order );
	}
}
add_action( 'wc_pip_after_footer', 'sv_wc_pip_add_order_barcode', 10, 4 );


function sv_wc_pip_add_order_barcode_styles() {
	?>
	#view-order-barcode {
		text-align: center;
	}
	<?php
}
add_action( 'wc_pip_styles', 'sv_wc_pip_add_order_barcode_styles' );
