<?php // only copy this line if needed

/**
 * Replace country codes with full country names in order exports generated by
 * Customer/Order/Coupon Export
 *
 * @param array $order_data the original column data
 * @param \WC_Order $order the order object
 * @param \CSV_Export_Generator $csv_generator the generator instance
 */
function sv_wc_csv_export_use_full_country_names( $order_data, $order, $csv_generator ) {

	$countries      = WC()->countries->get_countries();
	$new_order_data = array();

	$custom_data = array(
		'billing_country'  => isset( $countries[ $order->get_billing_country() ] )  ? $countries[ $order->get_billing_country() ]  : $order->get_billing_country(),
		'shipping_country' => isset( $countries[ $order->get_shipping_country() ] ) ? $countries[ $order->get_shipping_country() ] : $order->get_shipping_country(),
	);

	if ( sv_wc_csv_export_is_one_row( $csv_generator ) ) {

		foreach ( $order_data as $data ) {
			$new_order_data[] = array_merge( (array) $data, $custom_data );
		}

	} else {
		$new_order_data = array_merge( $order_data, $custom_data );
	}

	return $new_order_data;
}
add_filter( 'wc_customer_order_export_csv_order_row', 'sv_wc_csv_export_use_full_country_names', 10, 3 );


if ( ! function_exists( 'sv_wc_csv_export_is_one_row' ) ) :

/**
 * Helper function to check the export format
 *
 * @param \CSV_Export_Generator $csv_generator the generator instance
 * @return bool - true if this is a one row per item format
 */
function sv_wc_csv_export_is_one_row( $csv_generator ) {

	$one_row_per_item = false;

	if ( version_compare( wc_customer_order_csv_export()->get_version(), '4.0.0', '<' ) ) {

		// pre 4.0 compatibility
		$one_row_per_item = ( 'default_one_row_per_item' === $csv_generator->order_format || 'legacy_one_row_per_item' === $csv_generator->order_format );

	} elseif ( isset( $csv_generator->format_definition ) ) {

		// post 4.0 (requires 4.0.3+)
		$one_row_per_item = 'item' === $csv_generator->format_definition['row_type'];
	}

	return $one_row_per_item;
}

endif;
